### ISSUE TITLE
Broken Link: Example Usage

### ISSUE THREAD

**Issue by ckartik** [sei-protocol/sei-docs-old#107]
If you navigate to the link under [pre-compiled contracts](https://www.docs.sei.io/dev-interoperability#precompiled-contracts) and click on examples, you'll see that the following link is broken: https://www.docs.sei.io/precompiles/example-usage.

**Comment by cordt-sei** [comment]
Should be covered now, I forgot to include some way to identify these redirects to the 404 that doesn't tell you it's a 404.

https://github.com/sei-protocol/sei-docs/pull/112
