### ISSUE TITLE
Omitted guide section at /dev-querying-state

### ISSUE THREAD

**Issue by mighty-odewumi** [sei-protocol/sei-docs-old#147]
A section of the **Querying State** is missing information or intentionally left blank. 

Here's the URL: [Querying By Block Height](https://www.docs.sei.io/dev-querying-state#querying-by-block-height)

Was it omitted as it could possibly contain the same content as that in [Querying Historical State](https://www.docs.sei.io/dev-querying-state#querying-historical-state) section?

Could you please let me know what needs to be done there and I'd be glad to work on it?

**Comment by alexander-sei** [comment]
Hey, you saw that correctly, thanks for the tip.
