### ISSUE TITLE
Nit: We should make this list of tags a list of reusable enums

### ISSUE THREAD

**Issue by Cordtus** [sei-protocol/sei-docs-old#53]
Nit: We should make this list of tags a list of reusable enums
```ts
export enum Tag {
    WALLET = 'Wallet',
    NATIVE = 'Native',
    ...
}
```

Then for each app we can do `tags: [Tag.WALLET, Tag.NATIVE]` and not have to worry about ensuring all the apps have the same spelling, case etc when we add more in the future.

_Originally posted by @mj850 in https://github.com/sei-protocol/sei-docs/pull/52#discussion_r1594747605_

**Comment by cordt-sei** [comment]
Fixed in Devrel branch [upon merging ](https://github.com/sei-protocol/sei-docs/pull/56/commits).

Additionally added a doc for contributing to the ecosystem apps page at `./eco-apps.mdx`
