### ISSUE TITLE
More exhaustive list of RPCs for all chains

### ISSUE THREAD

**Issue by geauser** [sei-protocol/sei-docs-old#80]
Hi!

Is it possible to have more RPCs added on this [page](https://www.docs.sei.io/dev-ecosystem-providers/rpc-providers)?
Particularly the testnet ones? Could perhaps use this link but EVM endpoints are lacking: https://cosmos.directory/sei/nodes. 

Thanks a lot!

**Comment by cordt-sei** [comment]
That directory page is actually just generated from this [chain registry](https://github.com/cosmos/chain-registry). If you know of any others you can PR to the repo there. I think they have pretty much the same list as the Sei one does.
